import re
s = '''►Source Code + Text Tutorial - https://www.codewithharry.com/videos/...
►Full Python tutorials for absolute beginners (Hindi) playlist - https://www.youtube.com/playlist?list...
►Click here to subscribe - https://www.youtube.com/channel/UCeVM...


Best Hindi Videos For Learning Programming:

►Learn Python In One Video - https://www.youtube.com/watch?v=qHJjM...

►Learn JavaScript in One Video - https://www.youtube.com/watch?v=onbBV...

►Learn PHP In One Video - https://www.youtube.com/watch?v=xW7ro...

►Machine Learning Using Python - https://www.youtube.com/playlist?list...

►Creating & Hosting A Website (Tech Blog) Using Python - https://www.youtube.com/playlist?list...
'''
# patt = re.compile(r'Machine')
patt = re.compile(r'')

matches = patt.finditer(s)
for match in matches:
    print(match)
    print(s[508:515])
